### ISSUE TITLE
unable to create device handler

### ISSUE THREAD

**Issue by westiepark** [inpier/Fibaro-Dimmer-211#2]
i am knew to all this so  apologise if this is a basic error but when i try and create the device handler in the IDE it throws up exception errors

"Org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed: script14873380539161348487141.groovy: 53: expecting anything but ''\n''; got it anyway @ line 53, column 341. ragraph", element: "paragraph" ^ 1 error"

i have no idea what they mean but it wont appear to let me go any further

Thanks for the help

**Comment by inpier** [comment]
Try copying and creating again. The code has been modified as a syntax error crept in during the update.

**Comment by westiepark** [comment]
All sorted. Thanks
